// Date: 2/23/2019 12:35:32 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.shrub.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelComputerDesktop extends ModelBase
{
  //fields
    ModelRenderer Computer;
    ModelRenderer Frame_Right;
    ModelRenderer Frame_Left;
    ModelRenderer Frame_Bottom;
    ModelRenderer Frame_Top;
    ModelRenderer Screen;
    ModelRenderer Monitor_Big;
    ModelRenderer Monitor_Sml;
    ModelRenderer Stand;
    ModelRenderer Stand_base;
  
  public ModelComputerDesktop()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Computer = new ModelRenderer(this, 0, 0);
      Computer.addBox(0F, 20F, 0F, 14, 4, 12);
      Computer.setRotationPoint(-7F, 0F, -5F);
      Computer.setTextureSize(64, 32);
      Computer.mirror = true;
      setRotation(Computer, 0F, 0F, 0F);
      Frame_Right = new ModelRenderer(this, 0, 0);
      Frame_Right.addBox(13F, 1F, 0F, 1, 8, 1);
      Frame_Right.setRotationPoint(-8F, 9F, -3F);
      Frame_Right.setTextureSize(64, 32);
      Frame_Right.mirror = true;
      setRotation(Frame_Right, 0F, 0F, 0F);
      Frame_Left = new ModelRenderer(this, 4, 0);
      Frame_Left.addBox(-7F, 1F, -5F, 1, 8, 1);
      Frame_Left.setRotationPoint(1F, 9F, 2F);
      Frame_Left.setTextureSize(64, 32);
      Frame_Left.mirror = true;
      setRotation(Frame_Left, 0F, 0F, 0F);
      Frame_Bottom = new ModelRenderer(this, 0, 16);
      Frame_Bottom.addBox(1F, 0F, 0F, 12, 1, 1);
      Frame_Bottom.setRotationPoint(-7F, 9F, -3F);
      Frame_Bottom.setTextureSize(64, 32);
      Frame_Bottom.mirror = true;
      setRotation(Frame_Bottom, 0F, 0F, 0F);
      Frame_Top = new ModelRenderer(this, 26, 16);
      Frame_Top.addBox(1F, 2F, 0F, 12, 1, 1);
      Frame_Top.setRotationPoint(-7F, 16F, -3F);
      Frame_Top.setTextureSize(64, 32);
      Frame_Top.mirror = true;
      setRotation(Frame_Top, 0F, 0F, 0F);
      Screen = new ModelRenderer(this, 30, 24);
      Screen.addBox(-6F, 0F, 0F, 10, 8, 0);
      Screen.setRotationPoint(1F, 10F, -2.2F);
      Screen.setTextureSize(64, 32);
      Screen.mirror = true;
      setRotation(Screen, 0F, 0F, 0F);
      Monitor_Big = new ModelRenderer(this, 0, 18);
      Monitor_Big.addBox(-6F, 9F, -4F, 10, 8, 5);
      Monitor_Big.setRotationPoint(1F, 1F, 2F);
      Monitor_Big.setTextureSize(64, 32);
      Monitor_Big.mirror = true;
      setRotation(Monitor_Big, 0F, 0F, 0F);
      Monitor_Sml = new ModelRenderer(this, 30, 18);
      Monitor_Sml.addBox(0F, 11F, 0F, 6, 4, 2);
      Monitor_Sml.setRotationPoint(-3F, 1F, 3F);
      Monitor_Sml.setTextureSize(64, 32);
      Monitor_Sml.mirror = true;
      setRotation(Monitor_Sml, 0F, 0F, 0F);
      Stand = new ModelRenderer(this, 40, 0);
      Stand.addBox(0F, 0F, 0F, 4, 2, 2);
      Stand.setRotationPoint(-2F, 18F, -1F);
      Stand.setTextureSize(64, 32);
      Stand.mirror = true;
      setRotation(Stand, 0F, 0F, 0F);
      Stand_base = new ModelRenderer(this, 40, 4);
      Stand_base.addBox(-2F, 0F, 0F, 6, 1, 4);
      Stand_base.setRotationPoint(-1F, 19.5F, -2F);
      Stand_base.setTextureSize(64, 32);
      Stand_base.mirror = true;
      setRotation(Stand_base, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Computer.render(f5);
    Frame_Right.render(f5);
    Frame_Left.render(f5);
    Frame_Bottom.render(f5);
    Frame_Top.render(f5);
    Screen.render(f5);
    Monitor_Big.render(f5);
    Monitor_Sml.render(f5);
    Stand.render(f5);
    Stand_base.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  
  public void renderModel(float f, boolean on) {
	  Computer.render(f);
	  Frame_Right.render(f);
	  Frame_Left.render(f);
	  Frame_Bottom.render(f);
	  Frame_Top.render(f);
	  Screen.render(f);
	  Monitor_Big.render(f);
	  Monitor_Sml.render(f);
	  Stand.render(f);
	  Stand_base.render(f);
  }

}
